chore(fault-docs): Add GCP Azure AWS fault docs from OSS
chaosnative/developer-hub-cn pull request #21
Opened 2022-11-11 15:39 UTC by neelanjan00

# Harness Developer Pull Request
- Adds GCP fault docs from OSS
- Adds Azure fault docs from OSS
- Adds AWS fault docs from OSS
- Adds contents for k8s faults and other OSS faults
- Fix kubelet-density fault docs curly braces error

## What Type of PR is This?
- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

## House Keeping
Some items to keep track of. Screenshots of changes are optional but would help the maintainers review quicker. 
- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-11-12 06:01 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/aws/ebs-loss-by-id.md
> +  chaosServiceAccount: ebs-loss-by-id-sa
```suggestion
  chaosServiceAccount: litmus-admin
```

2022-11-12 06:02 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/aws/ebs-loss-by-id.md
> +  chaosServiceAccount: ebs-loss-by-id-sa
we have removed the experiment scoped RBAC from here. Let's use litmus-admin SA - applies for other docs as well

2022-11-12 06:04 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/aws/ebs-loss-by-id.md
> +          value: '<region for EBS_VOLUME_ID>'
let's provide a dummy value instead of a placeholder - as this is an example manifest

2022-11-14 04:48 UTC, avaakash requested changes

2022-11-14 04:48 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/ebs-loss-by-id.md
> +        <td> </td>
```suggestion
        <td> Eg: 30 </td>
```

2022-11-14 04:48 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/ebs-loss-by-id.md
> +        <td>  </td>
Can we provide example here for multiple IDs

2022-11-14 04:48 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/ebs-loss-by-id.md
> +        <td> </td>
Can we provide an example.

2022-11-14 08:03 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/aws/static/manifests/ebs-loss-by-id/ebs-volume-id.yaml
> +          value: '<region for EBS_VOLUME_ID>'
value: 'us-east-1'

2022-11-14 08:04 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/aws/static/manifests/ebs-loss-by-id/ebs-volume-id.yaml
> +  chaosServiceAccount: ebs-loss-by-id-sa
litmus-admin

2022-11-14 08:04 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/aws/static/manifests/ebs-loss-by-id/ebs-volume-id.yaml
> +  chaosServiceAccount: ebs-loss-by-id-sa
looks like you have changed it in .md file directly. You have to change it here then run the embedmd command

2022-11-14 08:09 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/chaos-faults.md
> +<<<<<<< HEAD
remove this

2022-11-14 08:35 UTC, ispeakc0de approved these changes

2022-11-14 08:35 UTC, merged