Chore(experiment): Adds AWS ECS experiment docs
chaosnative/developer-hub-cn pull request #25
Opened 2022-11-14 12:42 UTC by uditgaurav

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-11-14 13:56 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/aws/ecs-agent-stop.md
> +      </tr>
as suggested by @avaakash "We can remove these as the default document will be used for these experiments, if the user wants to use a custom document they can use the SSM Command experiment ( as discussed recently)"

2022-11-14 13:57 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/aws/ecs-agent-stop.md
> +      </tr>
as suggested by @avaakash "We can remove these as the default document will be used for these experiments, if the user wants to use a custom document they can use the SSM Command experiment ( as discussed recently)"

2022-11-14 13:58 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/aws/ecs-agent-stop.md
> +      </tr>
check other places too

2022-11-14 14:01 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/aws/ecs-container-io-stress.md
> +The worker's count for the stress can be tuned with NUMBER_OF_WORKERS ENV.
```suggestion
The worker's count for the stress can be tuned with `NUMBER_OF_WORKERS` ENV.
```

2022-11-14 14:05 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/aws/ecs-container-network-lantecy.md
> +        <td>  NETWORK_LATENCY </td>
NETWORK_INTERFACE, DESTINATION_IPS, and  DESTINATION_HOSTS  env are missing

2022-11-14 14:10 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/aws/ecs-container-network-lantecy.md
> +## Introduction
typo in the file name lantecy --> latency

2022-11-14 14:10 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/aws/ecs-container-network-lantecy.md
> +        <td>  NETWORK_LATENCY </td>
add these entries into table of .png image as well

2022-11-14 14:13 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/chaos-faults.md
> +    <td><a href="/docs/chaos-engineering/chaos-faults/aws/ecs-container-cpu-hog">ec2-dns-chaos</a></td>
```suggestion
    <td><a href="/docs/chaos-engineering/chaos-faults/aws/ecs-container-cpu-hog">ecs-container-cpu-hog</a></td>
```

2022-11-14 14:14 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/chaos-faults.md
> +    <td><a href="/docs/chaos-engineering/chaos-faults/aws/ecs-container-io-stress">ec2-dns-chaos</a></td>
```suggestion
    <td><a href="/docs/chaos-engineering/chaos-faults/aws/ecs-container-io-stress">ecs-container-io-stress</a></td>
```

2022-11-14 14:14 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/chaos-faults.md
> +    <td><a href="/docs/chaos-engineering/chaos-faults/aws/ecs-container-memory-hog">ec2-dns-chaos</a></td>
```suggestion
    <td><a href="/docs/chaos-engineering/chaos-faults/aws/ecs-container-memory-hog">ecs-container-memory-hog</a></td>
```

2022-11-14 14:15 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/chaos-faults.md
> +    <td>EC2 Network Latency</td>
```suggestion
    <td>ECS Container Network Latency</td>
```

2022-11-14 14:16 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/chaos-faults.md
> +    <td>EC2 Network Latency</td>
check other names and filepaths

2022-11-14 14:17 UTC, ispeakc0de commented on docs/chaos-engineering/chaos-faults/chaos-faults.md
> +    <td><a href="/docs/chaos-engineering/chaos-faults/aws/ecs-container-cpu-hog">ec2-dns-chaos</a></td>
check other places too

2022-11-14 14:31 UTC, avaakash requested changes

2022-11-14 14:31 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/ecs-agent-stop.md
> +        <th> Notes </th>
```suggestion
            <th> Variables </th>
            <th> Description </th>
            <th> Notes </th>
```
Can we add indentations in HTML code

2022-11-14 14:31 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/ecs-agent-stop.md
> +        <td>  </td>
We can add an example in the notes section (or default value) to maintain consistency in docs.

2022-11-14 14:31 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/ecs-container-cpu-hog.md
> +Disk Pressure or CPU hogs is another very common and frequent scenario we find with conrainers/applications that can result in the eviction of the application (task container) and impact its delivery
```suggestion
CPU hogs are another very common and frequent scenario we find with containers/applications that can result in the eviction of the application (task container) and impact its delivery. Such scenarios can still occur despite whatever availability aids docker provides. These problems are generally referred to as "Noisy Neighbour" problems.
```

2022-11-14 14:31 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/ecs-agent-stop.md
> +Agent chaos stop is another very common and frequent scenario we find with ECS clusters that can result in breaking of agent that manages task container on ECS cluster and impact its delivery. Such s
```suggestion
Agent chaos stop is another very common and frequent scenario we find with ECS clusters that can break an agent that manages the task container on the ECS cluster and impacts their delivery. Such scenarios can still occur despite whatever availability aids docker provides.
```

2022-11-14 14:31 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/ecs-container-cpu-hog.md
> +- ECS Container CPU hog contains chaos to disrupt the state of infra resources. The experiment can induce a stress chaos on AWS ECS container using Amazon SSM Run Command, this is carried out by usin
```suggestion
- ECS Container CPU hog contains chaos to disrupt the state of infra resources. The experiment can induce stress chaos on the AWS ECS container using Amazon SSM Run Command, this is carried out by using SSM Docs which is in-built into the experiment for the give chaos experiment.
```

2022-11-14 14:31 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/ecs-container-memory-hog.md
> +Memory usage within containers is subject to various constraints. If the limits are specified in their spec, exceeding them can cause termination of the container (due to OOMKill of the primary proce
```suggestion
Memory usage within containers is subject to various constraints. If the limits are specified in their spec, exceeding them can cause termination of the container (due to OOMKill of the primary process, often pid 1) - the restart of the container by docker, subject to the policy specified. For containers with no limits placed, the memory usage is uninhibited until such time as the VM level OOM Behaviour takes over. In this case, containers on the Instance can be killed based on their oom_score. This eval is extended to all task containers running on the instance - thereby causing a bigger blast radius.
```

2022-11-14 18:16 UTC, uditgaurav commented
@ispeakc0de / @avaakash Have addressed the comments

2022-11-15 05:05 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/aws/ecs-agent-stop.md
> +        <td> </td>
```suggestion
        <td> Eg. 30 </td>
```

2022-11-15 05:05 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/aws/ecs-container-cpu-hog.md
> +        <td>  </td>
```suggestion
        <td> Eg. cluster-1 </td>
```

2022-11-15 05:05 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/aws/ecs-container-cpu-hog.md
> +        <td> </td>
```suggestion
        <td> Eg. us-east-1 </td>
```

2022-11-15 11:49 UTC, neelanjan00 approved these changes

2022-11-15 11:55 UTC, avaakash approved these changes

2022-11-15 17:58 UTC, ispeakc0de approved these changes

2022-11-15 17:58 UTC, merged