Chore(lambda-chaos): Adds docs for AWS Lambda chaos to update function memory and timeout
chaosnative/developer-hub-cn pull request #34
Opened 2022-11-22 12:24 UTC by uditgaurav

It will add the docs for lambda function chaos to update memory limit and timeout value for a certain chaos duration to check the function stability.

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-11-22 14:13 UTC, avaakash requested changes

2022-11-22 14:13 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-memory.md
> +        <td> The region name of the target instance</td>
```suggestion
        <td> The region name of the target lambda function</td>
```

2022-11-22 14:13 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-memory.md
> +        <td> The total time duration for chaos insertion (sec) </td>
```suggestion
        <td> The total time duration for chaos insertion in seconds </td>
```

2022-11-22 14:13 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-memory.md
> +        <td> The interval (in sec) between successive instance termination.</td>
```suggestion
        <td> The interval (in seconds) between successive instance termination.</td>
```
IMO for docs using seconds would be a better approach

2022-11-22 14:13 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-memory.md
> +          value: 'chaos-function'
Since we do not provide any default value for `MEMORY_IN_MEGABYTES`, this configuration will not work. I guess we can remove this example.

2022-11-22 14:13 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-timeout.md
> +          value: 'chaos-function'
Similarly in this as well, we do not have any default value for `FUNCTION_TIMEOUT`

2022-11-22 14:13 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/chaos-faults.md
> +    <td>Lambda Update function Timeout</td>
```suggestion
    <td>Lambda Update Function Timeout</td>
```

2022-11-22 14:13 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/chaos-faults.md
> +    <td>Lambda Update function Memory</td>
```suggestion
    <td>Lambda Update Function Memory</td>
```

2022-11-22 16:07 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-memory.md
> +<summary>View the uses of the experiment</summary>
```suggestion
<summary>View the uses of the fault</summary>
```

2022-11-22 16:07 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-memory.md
> +Hitting a memory litmus is a very common and frequent scenario we find with lambda functions that can slow down the service and impacts their delivery. Such scenarios can still occur despite whatever
```suggestion
Hitting a memory limit is a very common and frequent scenario we find with lambda functions that can slow down the service and impacts their delivery. Such scenarios can still occur despite whatever availability aids AWS provides or we determine.
```

2022-11-22 16:07 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-memory.md
> +Running out of memory due to a smaller limit interrupts the flow of the given function. So this category of chaos experiment helps you to build immunity on the application undergoing any such scenari
```suggestion
Running out of memory due to a smaller limit interrupts the flow of the given function. So this category of chaos fault helps you to build immunity on the application undergoing any such scenarios.
```

2022-11-22 16:07 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-memory.md
> +## Experiment Examples
```suggestion
## Fault Examples
```

2022-11-22 16:07 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-timeout.md
> +<summary>View the uses of the experiment</summary>
```suggestion
<summary>View the uses of the fault</summary>
```

2022-11-22 16:07 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-timeout.md
> +Getting timeout errors interrupts the flow of the given function. So this category of chaos experiment helps you to build the immunity of the application undergoing any such scenarios.
```suggestion
Getting timeout errors interrupts the flow of the given function. So this category of chaos fault helps you to build the immunity of the application undergoing any such scenarios.
```

2022-11-22 16:07 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-timeout.md
> +## Experiment Tunables
```suggestion
## Fault Tunables
```

2022-11-22 16:07 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-timeout.md
> +    <summary>Check the Experiment Tunables</summary>
```suggestion
    <summary>Check the Fault Tunables</summary>
```

2022-11-22 16:07 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-timeout.md
> +## Experiment Examples
```suggestion
## Fault Examples
```

2022-11-22 16:07 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-timeout.md
> +Refer the [common attributes](../common-tunables-for-all-experiments) and [AWS specific tunable](./aws-experiments-tunables) to tune the common tunables for all experiments and aws specific tunables.
```suggestion
Refer the [common attributes](../common-tunables-for-all-experiments) and [AWS specific tunable](./aws-experiments-tunables) to tune the common tunables for all faults and aws specific tunables.
```

2022-11-24 07:16 UTC, uditgaurav commented
Closing this PR as it is added here - https://github.com/harness/developer-hub/pull/143

2022-11-24 07:16 UTC, closed without merging